module.exports = {
  components: [
    // 'virtual',
    // 'keyboard',
    // 'mousewheel',
    'navigation',
    'pagination',
    // 'scrollbar',
    // 'parallax',
    // 'zoom',
    // 'lazy',
    // 'controller',
    // 'a11y',
    // 'history',
    // 'hash-navigation',
    'autoplay',
    'effect-fade',
    // 'effect-cube',
    // 'effect-flip',
    // 'effect-coverflow',
    // 'thumbs',
  ],
  target: 'universal',
  themeColor: 'transparent',
  colors: {
    white: 'transparent',
    black: 'transparent',
  },
};
